site_name: Language Model Markdown

plugins:
  - search
  - mkdocstrings

theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true

nav:
  - index.md 
  - Handbook:
    - Handbook/Configuration.md
    - Handbook/Interaction.md
    - Handbook/PrepareRAG.md
  - Reference:
    - API/config.md
    - API/scan.md
    - API/markdown.md
    - API/tree.md
    - API/language_models.md
    - API/utils.md
  - About.md
